/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#4a4949",
        "on-secondary-fixed-variant": "#474646",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#3a3939",
        "on-primary-container": "#005b47",
        "surface-variant": "#353534",
        "outline-variant": "#3b4a44",
        "inverse-primary": "#006b54",
        "on-primary-fixed": "#002118",
        "primary-container": "#20dbaf",
        "secondary": "#c8c6c5",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "primary": "#50f8ca",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-container": "#4e5050",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "background": "#131313",
        "surface-container-high": "#2a2a2a",
        "surface-dim": "#131313",
        "on-secondary-container": "#bab8b7",
        "surface-tint": "#2adfb3",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#313030",
        "on-primary": "#00382a",
        "on-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "error": "#ffb4ab",
        "on-surface-variant": "#bacac2",
        "primary-fixed-dim": "#2adfb3",
        "outline": "#85948d",
        "surface-container": "#201f1f",
        "tertiary-container": "#c1c2c2",
        "on-primary-fixed-variant": "#00513f",
        "on-secondary-fixed": "#1c1b1b",
        "surface": "#131313",
        "secondary-fixed": "#e5e2e1",
        "on-error": "#690005",
        "primary-fixed": "#56fcce",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#2f3131",
        "tertiary-fixed-dim": "#c6c6c7",
        "tertiary": "#dedede",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed-variant": "#454747"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
